inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'exe/**/*'
    - 'fixtures/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
  DisplayCopNames: true


# It's ok to have more than one empty line to create a 'paragrapth'.
Layout/EmptyLines:
  Enabled: false

# Extra space is fine.
Layout/EmptyLinesAroundClassBody:
  Enabled: false

# Extra space is fine.
Layout/EmptyLinesAroundModuleBody:
  Enabled: false

# Normally one line in between, but two allowed for "paragraphs".
Layout/EmptyLineBetweenDefs:
  NumberOfEmptyLines: [1, 2]

# Rely on Git to normalize end of lines.
Layout/EndOfLine:
  Enabled: false

# Add lines as needed.
Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation


Naming/RescuedExceptionsVariableName:
  PreferredName: error


Metrics/AbcSize:
  Enabled: false
  Exclude:
    - test/**/*

Metrics/ClassLength:
  Exclude:
    - test/**/*

# Too noisy.
Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Exclude:
    - features/step_definitions/**/*

Metrics/MethodLength:
  Exclude:
    - test/**/*

# Too noisy.
Metrics/PerceivedComplexity:
  Enabled: false


# Nah, sometimes easier to read with accessors having separate grouping.
Style/AccessorGrouping:
  Enabled: false

# Prefer { ... } over do ... end except for control flow and
# method defintions. Unfortunatly, no cop configuration for this.
# https://github.com/chneukirchen/styleguide/blob/e60de37b478d3f892f6985a58d573016f33f0269/RUBY-STYLE#L63-L67
Style/BlockDelimiters:
  EnforcedStyle: semantic
  Enabled: false

# Generally prefer compact style to reduce indentation. But no hard rule.
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Enabled: false

# This doesn't always read nicely.
Style/ConditionalAssignment:
  Enabled: false

# Nah, it's ok.
Style/CommentedKeyword:
  Enabled: false

# TODO(thomthom): Consider turning this back on.
Style/Documentation:
  Enabled: false

# Conflict too often with Metric/LineLength.
# https://github.com/bbatsov/rubocop/issues/1332#issuecomment-277503854
Style/GuardClause:
  Enabled: false

# In the context of the Thor DLS the rocket arrow => reads better.
Style/HashSyntax:
  Exclude:
    - app/commands/**/*

# Some times it reads clearer to not trail if/unless at the end.
Style/IfUnlessModifier:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

# %w and %i etc isn't really intuitive unless you are really familiar with the
# syntax. %w seems used often enough. But [:symbol, :foo] reads clearer than
# %i(symbol foo).
Style/SymbolArray:
  Enabled: False

# Add trailing comma so it's easy to duplicate/add lines.
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
